site_name: ML Base
theme:
  name: "material"
repo_url: https://github.com/schmidtbri/ml-base
site_description: ML Base Package Documentation
copyright: 2021, Brian Schmidt
nav:
    - Home: index.md
    - Examples:
      - Basic Examples: basic.md
      - Decorator Examples: decorator.md
    - API: api.md
markdown_extensions:
  - admonition
plugins:
  - search
  - mkdocstrings
