name: "Build Documentation"

on:
  push:
    branches:
      - '*'
      - '!master'
  release:
    branches:
      - master
    types:
      - created

jobs:

  documentation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Update Tools"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel

      - name: "Install Dependencies"
        run: make dependencies

      - name: "Install Doc Dependencies"
        run: make doc-dependencies

      - name: "Build Documentation"
        run: make build-docs

      - name: "Archive Documentation"
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: site
