name: "Upload Python Package"

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Set up Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: "Install and Upgrade Dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade twine

    - name: "Add Release Version"
      env:
        SOURCE_TAG: ${{ github.event.release.tag_name }}
      run: |
        echo "${SOURCE_TAG:1}" > ml_base/version.txt

    - name: "Build Package"
      run: make build

    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5.1

    - name: "Publish to Test PyPi"
      if: steps.branch-name.outputs.ref_branch != 'main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: |
        echo "${{ steps.branch-name.outputs.ref_branch }}"
        twine upload dist/*

    - name: "Build and Publish to PyPi"
      if: steps.branch-name.outputs.ref_branch == 'main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        echo "${{ steps.branch-name.outputs.ref_branch }}"
        twine upload dist/*
