name: Upload Python Package

on:
  release:
    types: [created]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install and Upgrade Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade twine

    - name: Add Release Version
      env:
        SOURCE_TAG: ${{ github.event.release.tag_name }}
      run: |
        sed 's/<version_placeholder>/'"${SOURCE_TAG:1}"'/g' ml_base/__init__.py > __init__.py
        mv __init__.py ml_base/__init__.py

    - name: Build and Publish to Test PyPi
      if: github.ref != 'refs/heads/master'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: |
        make build
        twine upload dist/*

    - name: Build and Publish to PyPi
      if: github.ref == 'refs/heads/master'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        make build
        twine upload dist/*
