name: "Upload Python Package"

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: "Install and Upgrade Dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade twine
    - name: "Add Release Version"
      env:
        SOURCE_TAG: ${{ github.event.release.tag_name }}
      run: |
        echo -n "${SOURCE_TAG:1}" > ml_base/version.txt
    - name: "Build Package"
      run: make build
    - name: "Publish to PyPi"
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        twine upload dist/*
