name: "Inspect and Test Code"

on:
  pull_request:
    branches:
      - main

# TODO: add dependency caching
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Set up Python 3.9"
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: "Install Dependencies"
      run: make dependencies
    - name: "Install Test Dependencies"
      run : make test-dependencies
    - name: "Check Codestyle"
      run: make check-codestyle
    - name: "Check Docstyle"
      run: make check-docstyle
    - name: "Code Metrics"
      run: make check-codemetrics
    - name: "Security Issues"
      run: make check-security
    - name: "Dependency Security"
      run: make check-dependencies

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install Dependencies"
      run: make dependencies
    - name: "Install Test Dependencies"
      run: make test-dependencies
    - name: "Run Unit Tests"
      run: make test-reports
    - name: "Archive Unit Test Report"
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-report
        path: reports/unit_tests
    - name: "Archive Code Coverage Report"
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: reports/coverage